// utils/word.ts

export const WORD_LIST = [
  // Original words
  'galaxy', 'rocket', 'magnet', 'legend', 'humane', 'fusion', 'goblet', 'jungle',
  'luxury', 'napkin', 'oxygen', 'pepper', 'quartz', 'refine', 'spiral', 'turkey', 
  'unfold', 'violet', 'wander', 'zodiac', 'kitten', 'bottle', 'planet', 'window', 
  'bright', 'stream', 'puzzle', 'animal', 'bridge', 'circle', 'dreamy', 'energy', 
  'fabric', 'gentle', 'honest', 'insect', 'jumper', 'kernel', 'laptop', 'museum', 
  'noodle', 'object', 'pirate', 'quieto', 'rabbit', 'shield', 'ticket', 'united', 
  'victor', 'wonder', 'xenial', 'yellow', 'zenith',
  
  // Additional common 6-letter words
  'action', 'active', 'actual', 'adjust', 'advice', 'affair', 'agenda', 'almost',
  'always', 'amount', 'ancient', 'answer', 'anyone', 'appear', 'around', 'arrive',
  'artist', 'aspect', 'assess', 'assist', 'assume', 'attach', 'attack', 'attend',
  'author', 'autumn', 'avenue', 'backed', 'barely', 'barrel', 'battle', 'beauty',
  'became', 'become', 'before', 'behind', 'belong', 'better', 'beyond', 'binary',
  'branch', 'breath', 'breeze', 'budget', 'bullet', 'bundle', 'burden', 'bureau',
  'button', 'camera', 'campus', 'cancel', 'cancer', 'candid', 'canvas', 'carbon',
  'career', 'carpet', 'carrot', 'castle', 'casual', 'center', 'census', 'chance',
  'change', 'chapel', 'charge', 'charity', 'cheese', 'cherry', 'choice', 'choose',
  'chorus', 'chosen', 'church', 'cinema', 'circle', 'circus', 'cities', 'citrus',
  'civics', 'clarity', 'classic', 'client', 'climate', 'clinic', 'closed', 'closer',
  'coffee', 'column', 'combat', 'comedy', 'coming', 'commit', 'common', 'comply',
  'copper', 'corner', 'cosmic', 'cotton', 'county', 'couple', 'course', 'covers',
  'create', 'credit', 'crisis', 'cruise', 'custom', 'damage', 'danger', 'dealer',
  'debate', 'decade', 'decide', 'defeat', 'defend', 'define', 'degree', 'demand',
  'depend', 'deputy', 'desert', 'design', 'desire', 'detail', 'detect', 'device',
  'devote', 'differ', 'dinner', 'direct', 'donate', 'double', 'dollar', 'domain',
  'driver', 'easier', 'effect', 'effort', 'either', 'eleven', 'emerge', 'empire',
  'employ', 'enable', 'ending', 'endure', 'energy', 'engage', 'engine', 'enough',
  'ensure', 'entire', 'entity', 'equity', 'escape', 'estate', 'ethics', 'ethnic',
  'evolve', 'exceed', 'except', 'excess', 'excuse', 'exempt', 'existe', 'expand',
  'expect', 'expert', 'export', 'expose', 'extend', 'extent', 'fabric', 'facing',
  'factor', 'failed', 'fairly', 'fallen', 'family', 'famous', 'farmer', 'faster',
  'father', 'fellow', 'female', 'figure', 'filing', 'finger', 'finish', 'fiscal',
  'fisher', 'flight', 'flower', 'flying', 'follow', 'forced', 'forest', 'forget',
  'formal', 'format', 'former', 'foster', 'fought', 'fourth', 'friend', 'fringe',
  'frozen', 'future', 'garden', 'gather', 'gender', 'genius', 'gentle', 'giving',
  'glance', 'global', 'golden', 'gospel', 'gotten', 'govern', 'grants', 'gravel',
  'ground', 'growth', 'guilty', 'handle', 'happen', 'harbor', 'hardly', 'health',
  'heaven', 'height', 'hidden', 'holder', 'honest', 'horror', 'hostel', 'hungry',
  'hurdle', 'immune', 'impact', 'import', 'impose', 'income', 'indeed', 'indoor',
  'inform', 'injury', 'inland', 'inmate', 'inside', 'intend', 'intent', 'invest',
  'island', 'isolate', 'issued', 'jacket', 'joiner', 'joined', 'joint', 'journey',
  'joyful', 'judged', 'judges', 'jungle', 'junior', 'keeper', 'kicked', 'kidney',
  'killed', 'kindly', 'knight', 'knowing', 'launch', 'lawyer', 'leader', 'league',
  'legacy', 'length', 'lesson', 'letter', 'liberty', 'library', 'license', 'likely',
  'listen', 'little', 'living', 'loaded', 'locked', 'lonely', 'longer', 'looked',
  'losing', 'luxury', 'mainly', 'making', 'manage', 'manner', 'manual', 'marble',
  'margin', 'marine', 'marked', 'market', 'master', 'matter', 'mature', 'medium',
  'member', 'memory', 'mental', 'merely', 'merger', 'method', 'middle', 'minute',
  'mirror', 'missile', 'mission', 'mistake', 'misuse', 'mobile', 'modern', 'modest',
  'module', 'moment', 'monkey', 'month', 'mostly', 'mother', 'motion', 'moving',
  'murder', 'museum', 'mutual', 'myself', 'narrow', 'nation', 'native', 'nature',
  'nearby', 'nearly', 'needle', 'neutral', 'newest', 'nicely', 'nobody', 'normal',
  'notice', 'notify', 'notion', 'number', 'object', 'obtain', 'occupy', 'office',
  'offset', 'online', 'option', 'orange', 'origin', 'output', 'oxygen', 'palace',
  'parent', 'partly', 'patent', 'paying', 'peanut', 'people', 'period', 'permit',
  'person', 'phrase', 'picked', 'pillar', 'planet', 'player', 'please', 'plenty',
  'plural', 'pocket', 'poetry', 'police', 'potato', 'policy', 'portal', 'portion', 'postal',
  'potato', 'powder', 'prayer', 'prefer', 'pretty', 'prince', 'prison', 'profit',
  'prompt', 'proper', 'proved', 'public', 'pulled', 'pursue', 'pushed', 'puzzle',
  'python', 'quarter', 'queens', 'queued', 'quicky', 'purely', 'quality', 'quest',
  'random', 'rarely', 'rather', 'rating', 'reader', 'really', 'reason', 'recall',
  'recipe', 'record', 'reduce', 'reform', 'regard', 'regime', 'region', 'regret',
  'reject', 'relate', 'relief', 'remain', 'remind', 'remote', 'remove', 'repair',
  'repeat', 'report', 'rescue', 'resent', 'resist', 'resort', 'result', 'resume',
  'retail', 'retain', 'return', 'reveal', 'review', 'reward', 'rhythm', 'ribbon',
  'rights', 'ritual', 'robust', 'rocket', 'rolled', 'roster', 'rotate', 'rubber',
  'ruling', 'runner', 'sacred', 'safety', 'salary', 'sample', 'saving', 'saying',
  'scheme', 'school', 'scored', 'screen', 'script', 'search', 'season', 'second',
  'secret', 'sector', 'secure', 'seeing', 'select', 'seller', 'senior', 'sensor',
  'server', 'settle', 'severe', 'sexual', 'shadow', 'shaped', 'shared', 'sharpy',
  'sheets', 'shells', 'shield', 'shifts', 'shined', 'shorts', 'should', 'showed',
  'signal', 'silent', 'silver', 'simple', 'simply', 'singer', 'single', 'sister',
  'sketch', 'skills', 'sleeve', 'slight', 'slowly', 'smooth', 'social', 'socket',
  'soften', 'solely', 'solids', 'solved', 'sooner', 'sorted', 'sought', 'sounds',
  'source', 'speech', 'sphere', 'spirit', 'splits', 'spoken', 'sports', 'spring',
  'square', 'stable', 'staged', 'stakes', 'stands', 'staple', 'stated', 'status',
  'stayed', 'stolen', 'stores', 'strain', 'stream', 'street', 'stress', 'strict',
  'strike', 'string', 'strong', 'struck', 'studio', 'submit', 'subtle', 'sudden',
  'suffer', 'suited', 'summer', 'summit', 'supply', 'surely', 'survey', 'switch',
  'symbol', 'system', 'taking', 'talent', 'talked', 'target', 'taught', 'tenant',
  'tender', 'tennis', 'thanks', 'theory', 'thirty', 'though', 'thread', 'throat',
  'throne', 'thrown', 'ticket', 'timber', 'timely', 'timing', 'tissue', 'toward',
  'traced', 'tracks', 'trader', 'trails', 'trains', 'trauma', 'travel', 'treaty',
  'trends', 'trials', 'tribal', 'trying', 'turned', 'twelve', 'twenty', 'unable',
  'unique', 'united', 'unless', 'unlike', 'update', 'upload', 'upward', 'useful',
  'vacant', 'vacuum', 'valley', 'valued', 'values', 'vendor', 'venue', 'verbal',
  'verify', 'versus', 'vessel', 'victim', 'violin', 'virtue', 'vision', 'visits',
  'visual', 'volume', 'voyage', 'waited', 'walked', 'wallet', 'wander', 'wanted',
  'warmed', 'warned', 'washed', 'wasted', 'watched', 'waters', 'wealth', 'weapon',
  'weekly', 'weight', 'wheels', 'whilst', 'widely', 'widens', 'widest', 'widget',
  'Window', 'winner', 'winter', 'wisdom', 'within', 'wizard', 'wonder', 'wooden',
  'worked', 'worker', 'worthy', 'writer', 'writer', 'yellow', 'zenith', 'zipped'
];
  
  export function getRandomWord(): string {
    return WORD_LIST[Math.floor(Math.random() * WORD_LIST.length)];
  }
  
  export function getDailyWord(): string {
    const today = new Date().toISOString().split('T')[0];
    const seed = [...today].reduce((acc, char) => acc + char.charCodeAt(0), 0);
    return WORD_LIST[seed % WORD_LIST.length];
  }
  